CREATE DATABASE CadastroProduto
GO

USE [CadastroProduto]
GO

CREATE TABLE dbo.Produto (
	Id int IDENTITY(1,1) NOT NULL,
	Nome varchar(100) NOT NULL,
	Valor decimal(18, 5) NOT NULL,
	ImagemURL varchar(250) NULL,
	DataCriacao datetime NOT NULL,

	CONSTRAINT PK_Produto PRIMARY KEY CLUSTERED 
	(
		Id ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO